### PR TITLE
fix build on gcc < 4.7 + add test for check_sin() in rf_test -c

### PR DESCRIPTION
**Pull request by wtarreau**
It took me some head scratching to figure why my atom was failing on this (I used clz instead of clzl) and I realized that it would be useful to have more error detection in rf_test so I called check_sin() as well.

The perf on my atom is now:
```
59 hashes, 1.000 sec, 2 threads, 58.995 H/s, 29.497 H/s/thread
55 hashes, 1.000 sec, 2 threads, 54.995 H/s, 27.498 H/s/thread
60 hashes, 1.000 sec, 2 threads, 59.994 H/s, 29.997 H/s/thread
58 hashes, 1.000 sec, 2 threads, 57.994 H/s, 28.997 H/s/thread
```
By the way it's not an N410 but a D510 (dual-core with HT disabled).

### CODE REVIEW

**Comment by bschn2** [comment]
Thank you Sir!

**Comment by itwysgsl** [comment]
Hello @wtarreau, just want to let you know that `&& !defined(__clang__)` cause error during compilation on macOS
https://github.com/bschn2/rainforest/pull/10/commits/ca5d1371691f82f619bff91102e326435d5323d2#diff-f9cd65a50b9d6828be5991f7d6f05e3dR256

P.s. Here is error message, seams like `__builtin_clrsbl` function is not declared with this clang check
```
rfv2/rfv2_core.c:291:6: error: use of unknown builtin '__builtin_clrsbl' [-Wimplicit-function-declaration]
```

**Comment by wtarreau** [comment]
On Mon, Apr 01, 2019 at 09:46:18PM -0700, iamstenman wrote:
> Hello @wtarreau, just want to let you know that `&& !defined(__clang__)` cause error during compilation on macOS
> https://github.com/bschn2/rainforest/pull/10/commits/ca5d1371691f82f619bff91102e326435d5323d2#diff-f9cd65a50b9d6828be5991f7d6f05e3dR256

Ah, so this means that clang doesn't have this builtin! I thought it
did since in general it tries to keep up with gcc on this.

Thanks,
Willy

**Comment by itwysgsl** [comment]
@wtarreau this https://github.com/bschn2/rainforest/pull/13 pull request should fix it :)
